#mysql连接信息
mysql_config:
  host: 129.28.178.16
  port: 3306
  db_name: online_judge
  user: online_judge
  password: yb123

#题目的存储信息
problem_config:
  work_dir: solution
  data_dir: problem

#队列的信息
thread_config:
  queue_size: 20
  count_thread: 5
